// import { useState } from "react";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { cookies } from "next/headers";
import Nav from "./Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  let getMode = cookies().get("mode");

  return (
    <html lang="en">
      <body
        className={
          getMode.value !== undefined && (getMode.value == "dark" ? "dark" : "")
        }
      >
        <Nav session={session} />
        {children}
      </body>
    </html>
  );
}
